### ISSUE TITLE
GeneralError: Cannot read property 'remove' of undefined

### ISSUE THREAD

**Issue by musicformellons** [thosakwe/feathers-seeder#20]
I am getting:

```
info: Feathers application started on http://localhost:8089
error: Unhandled Rejection at: Promise  Promise {
  <rejected> { GeneralError: Cannot read property 'remove' of undefined
    at new GeneralError (/home/usr/api_server/node_modules/feathers-errors/lib/index.js:177:17)
    at /home/usr/api_server/node_modules/feathers-seeder/lib/index.js:45:15
    at <anonymous>
    at runMicrotasksCallback (internal/process/next_tick.js:121:5)
    at _combinedTickCallback (internal/process/next_tick.js:131:7)
    at process._tickCallback (internal/process/next_tick.js:180:9)
    at Function.Module.runMain (module.js:684:11)
    at startup (bootstrap_node.js:191:16)
    at bootstrap_node.js:613:3
  type: 'FeathersError',
  name: 'GeneralError',
  message: 'Cannot read property \'remove\' of undefined',
  code: 500,
  className: 'general-error',
  data: undefined,
  errors: {} } } GeneralError: Cannot read property 'remove' of undefined
    at new GeneralError (/home/usr/api_server/node_modules/feathers-errors/lib/index.js:177:17)
    at /home/usr/api_server/node_modules/feathers-seeder/lib/index.js:45:15
    at <anonymous>
    at runMicrotasksCallback (internal/process/next_tick.js:121:5)
    at _combinedTickCallback (internal/process/next_tick.js:131:7)
    at process._tickCallback (internal/process/next_tick.js:180:9)
    at Function.Module.runMain (module.js:684:11)
    at startup (bootstrap_node.js:191:16)
    at bootstrap_node.js:613:3

```
my config:
```
const moment = require('moment');

module.exports = {
  count: 10,
  // delete: true,
  disabled: false,
  params: {seeder: 'true'},
  services: [
    {
      path: 'users.service.js',
      template: {
        name: '{{name.firstName}} {{name.lastName}}',
        password: '{{internet.password}}',
        username: '{{internet.userName}}',
        email: '{{internet.email}}',
        created_at: () => moment().subtract(7, 'days').format()
      }
    }
  ]
};
```

**Comment by musicformellons** [comment]
Do not know exactly what was going wrong, but have it working now... Might have been authentication related which I switched off, or I synced at wrong moment...
