### ISSUE TITLE
Error on postinstall (Unknown plugin "add-module-exports")

### ISSUE THREAD

**Issue by BafS** [thosakwe/feathers-seeder#3]
Hello,

I am not able to install feathers-seed, here is the log:

```sh
> feathers-seeder@1.0.2 postinstall /Users/.../backend/node_modules/feathers-seeder
> npm run compile

> feathers-seeder@1.0.2 compile /Users/.../backend/node_modules/feathers-seeder
> rimraf lib/ && babel -d lib/ src/

ReferenceError: Unknown plugin "add-module-exports" specified in "/Users/.../backend/node_modules/feathers-seeder/.babelrc" at 0, attempted to resolve relative to "/Users/.../backend/node_modules/feathers-seeder"
    at /usr/local/lib/node_modules/babel-cli/node_modules/babel-core/lib/transformation/file/options/option-manager.js:177:17
    at Array.map (native)
    at Function.normalisePlugins (/usr/local/lib/node_modules/babel-cli/node_modules/babel-core/lib/transformation/file/options/option-manager.js:153:20)
    at OptionManager.mergeOptions (/usr/local/lib/node_modules/babel-cli/node_modules/babel-core/lib/transformation/file/options/option-manager.js:245:36)
    at OptionManager.init (/usr/local/lib/node_modules/babel-cli/node_modules/babel-core/lib/transformation/file/options/option-manager.js:383:12)
    at File.initOptions (/usr/local/lib/node_modules/babel-cli/node_modules/babel-core/lib/transformation/file/index.js:223:65)
    at new File (/usr/local/lib/node_modules/babel-cli/node_modules/babel-core/lib/transformation/file/index.js:140:24)
    at Pipeline.transform (/usr/local/lib/node_modules/babel-cli/node_modules/babel-core/lib/transformation/pipeline.js:46:16)
    at transform (/usr/local/lib/node_modules/babel-cli/lib/babel/util.js:52:22)
    at Object.compile (/usr/local/lib/node_modules/babel-cli/lib/babel/util.js:61:12)
```

Thanks in advance !

**Comment by thosakwe** [comment]
Thanks, will get on this right now.

**Comment by thosakwe** [comment]
Just pushed 68bde6ef2d7c55cc33da59820338fb1d855bd26d.
